### ISSUE TITLE
Bug with the keyboard, impossible to click on options

### ISSUE THREAD

**Issue by azurejoga** [CG8516/PvZA11y#1]
Hello, @CG8516  I am facing the following errors while starting the game.

Starting...
Searching for game process...
D:\mods plant\Plants.Vs.Zombies.GOTY\Plants Vs Zombies GOTY\Plants vs. zombies
Thread count: 24
Failed to find 'keyboardInputDisable1' code!
Failed to find 'keyboardInputDisable2' code!
Failed to find 'keyboardInputDisable3' code!
Finished patching
DidOpen:True
prevScene: Board
Click on a seed packet to pick it up!
Continue Game?
Do you want to continue your current game, or restart the level?

When I press any key, nothing happens, as if it was failing to find the keys mapped by default in the mod.

I looked at the crashlog.txt and the following content is displayed.

The method or operation is not implemented. at PvZA11y.Widgets.Placeholder.Interact(InputIntent intent)
    at PvZA11y.Program.DoWidgetInteractions(Widget currentWidget, Input input)
    at PvZA11y.Program.SafeMain(String[] args)
    at PvZA11y.Program.Main(String[] args)Void Interact(PvZA11y.InputIntent)System.Collections.ListDictionaryInternal

Unfortunately, I can't access the game's options or do anything.
I tried it with the mouse and it worked, I think the problems are with the keys.

Furthermore: Apparently a stupid term appears on the screen to accept, which is not accessible with the mod or the mouse

I will attach all the files here for better understanding
[Crashlog.txt](https://github.com/CG8516/PvZA11y/files/13636137/Crashlog.txt)

**Comment by mojsior** [comment]
I also can not activate any option with keyboard. I tried plug in a x"xbox controller, but I can move around settings but I can not click.

**Comment by CG8516** [comment]
Thanks for the bug report!
Unfortunately, I'm not able to reproduce the issue on any of my test systems.

I've just made a new update, which uses an alternate method of sending clicks.
Let me know if the new update fixes it for you.

**Comment by inkydragon** [comment]
I don't get a similar error, but I've also run into problems when using keyboard-only operations.

<img width="1080" alt="vDSvUFSe1k" src="https://github.com/CG8516/PvZA11y/assets/5158738/c93e1a2a-53d8-41f2-82a5-eac6dfe63092">

In the screenshot, I'm using the keyboard to operate PvZ, switching buttons with the arrow keys.
In the picture, it switches to the Quit button, but the mouse is outside the window.
Pressing Enter at this point has no effect.

I guess it may have something related to the zooming in at the system level.


My env:
- Win 11
- Screen: 2560x1600, zoom x150%
- PvZ: Steam GOTY Edition, Not Full Screen, Window Mode
- Mod: master - d59d439, Debug mode, with VS2022

**Comment by CG8516** [comment]
@inkydragon Thank you for that report! I'm able to reproduce the problem when changing my display scaling.
Working on a fix now. Hopefully it's the same issue that others have been facing.

**Comment by CG8516** [comment]
Implemented a fix in Beta 1.5
