### ISSUE TITLE
There are only sound cues in the garden.

### ISSUE THREAD

**Issue by piano777wzy** [CG8516/PvZA11y#10]
If this is a bug, can it be repaired?

**Comment by CG8516** [comment]
I'm not entirely sure what you mean by that, but there should be sound cues and narration everywhere in the game.

**Comment by piano777wzy** [comment]
OK,&nbsp;well,&nbsp;that&nbsp;is,&nbsp;there&nbsp;is&nbsp;a&nbsp;problem.&nbsp;After&nbsp;buying&nbsp;the&nbsp;wisdom&nbsp;tree&nbsp;from&nbsp;the&nbsp;store,&nbsp;how&nbsp;to&nbsp;check&nbsp;the&nbsp;height&nbsp;after&nbsp;planting&nbsp;it?








 ---Original---
From: ***@***.***&gt;
Date: Tue, Dec 19, 2023 18:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CG8516/PvZA11y] There are only sound cues in the garden. (Issue#10)




 
The Zen Garden is supported, but there isn't an in-game guide yet.
 
Controls:
  
Up/Down/Left/Right: Navigate the garden, like the lawn.
 
CycleLeft/CycleRight: Switch garden tools.
 
Info1: Say what's on the current tile.
 
Info2: Say what the current plant needs.
 
Info3: Say how many plants need attention.
 
Option: Open the store.
  
When moving around the garden, the beep will change if you move to a plant that needs attention.
 
If any of those features aren't working, let me know.
 
&mdash;

**Comment by CG8516** [comment]
Press info1 while on the tree's page to check its height. 

Also, something might be wrong with your email client. Every space turned into "&nbsp;" which made your message very hard to read.

**Comment by CG8516** [comment]
Input cues have been added in Beta 1.12, to avoid others having the same issue.
