### ISSUE TITLE
Issue with Reassigning Keys and Functionality Interruption

### ISSUE THREAD

**Issue by Cyrax2001** [CG8516/PvZA11y#11]
Hello, mi friend, it seems we've encountered a little issue.
Let me explain. Typically, I reassign the inputs for Info 1, Info 2, Info 3, and Info 4 to buttons other than the function keys. The problem arises because I can't use them comfortably on my PC. To use the function keys correctly, I need to press the FN key. So, when I started playing, it seems that the keys I had configured were reset. When I tried to reassign them, I couldn't. Simply put, when it asks me to press the key for the upward arrow, it doesn't provide any further instructions and literally becomes unresponsive. I have to restart the mod to be able to use it, and I still can't reassign these keys.
Thank you very much for your work, my friend.

**Comment by CG8516** [comment]
Oh damn, sorry to hear that.  
I haven't been able to trigger the issue on my end, so it might be a tricky one to fix.  

Just to be sure. Are you using the 'rebind all keyboard inputs' option, or the 'rebind all controller buttons' option?  
If you choose the controller one, it will only listen for controller inputs, or the escape key, which should back out of the menu.  

If you're definitely using the keyboard one, could you let me know the last version that works for you? That will really help with narrowing down the cause.

**Comment by Cyrax2001** [comment]
mi friend, I sincerely apologize, but I've experienced the representation of a certain phrase we have here where I come from. The phrase is something like: "What is the best way to fix the car? Calling a mechanic." It refers to the idea that when something isn't working and you try to demonstrate it, for some reason, it starts working again.
I attempted to reproduce the issue to show you the messages sent to the cmd, but when I tried, everything worked perfectly once again. I apologize a thousand times, and please know that you're doing an excellent job with this mod.

**Comment by CG8516** [comment]
Haha, no problem at all. I'm glad it's working for you now :)
