### ISSUE TITLE
Small Gameplay Improvement Suggestions for Plants vs Zombies

### ISSUE THREAD

**Issue by Cyrax2001** [CG8516/PvZA11y#12]
1.
Slot Movement Sound Adjustment:
•
Proposal: Allow users to eliminate or disable the beep sound when moving over a plant using the slots.
•
Rationale: The sound may be considered unnecessary since, with the use of numeric keys, the information provided by the beep is practically redundant.
2.
Enhanced Screen Reader Presence:
•
Proposal: Increase the presence of the screen reader in providing indications, potentially through an accessibility menu option.
•
Rationale: While not suggesting the removal of existing audio cues, having the screen reader convey certain information, such as plant recharge status or zombie death, could enhance the gaming experience.
3.
Proximity Alert for Zombies:
•
Proposal: Introduce an alert when zombies approach the planting area, with customizable parameters.
•
Parameters:
•
Option to activate or deactivate the alert.
•
Choose which column triggers the alert (A, B, C, D, or E).
•
Rationale: Particularly beneficial for newcomers in the early game levels, this feature can provide additional assistance in tower defense gameplay, especially before the player becomes accustomed to filling the entire garden with plants.
4.
New Plant Inventory Sound Cue:
•
Proposal: Utilize the fully charged sound in conveyor belt levels to indicate when a new plant is added to the inventory.
•
Rationale: This would provide clarity on when a new enabled plant becomes available for use, enhancing player awareness during gameplay.

**Comment by CG8516** [comment]
Thanks for the suggestions!  

1. I just made some changes yesterday, to allow users to adjust the volume of each cue. It will be in the next update.  

2. I'll work on adding optional screenreader feedback for more of the audio cues.  
Though I'm concerned about the alerts frequently interrupting speech.  
If you were in the middle of listening to a zombie sonar scan, it would get interrupted with a "Plant ready", or "Zombie died on A 7", etc..  

I could work around that by implementing a message queueing system, but that brings additional problems.  
Imagine killing a wave of zombies, and having 20 "zombie died" messages queued.  
You wouldn't be able to hear your sonar results or board position, until it finished saying the list of dead zombies.  
Either way, it's going to take a fair bit of time and effort to balance it in a way that's informative, without being obnoxious.  

3. Great idea!  
Should it trigger every time a zombie passes through the column? Or just once for each 'group' of zombies?  
Or what about a constant background sound, like a low hum or rumbling, which plays while any zombie is on the left side of that column?  

4. Sure thing! Will be in the next update.

**Comment by Cyrax2001** [comment]
You're right about point 2. Perhaps my proposal for the screen reader to vocalize things like zombie deaths would be cumbersome, and implementing a message queuing system might overload things. Well, then I'll switch this proposal for another one. When you hover over a plant during gameplay, have it tell you the amount of sun it costs and if it can be used.
An example of how it could look is something like:
"Sunflower ready! 25 sun."
This way, newcomers can devise more effective strategies and better understand the characteristics of the plants.
Regarding point 3, let me explain my idea. How about we make it work with 2 zombies? I'm not sure if you'll be able to, but it would be good if you could program it so that if 2 or more zombies cross the line, the alert sound plays. But it should only work with 2 or more zombies. If you kill one of those that crossed, it will turn off. If there's only one zombie, and another arrives, it will activate. With this in mind, it is understood that if 2 zombies that were in the same tile pass, it will activate.
About the sound the alert could have... I don't know, but I suggest that you can toggle between off, verbal announcement, and sound announcement. And that the verbal announcement be as simple as... "Alert"!

**Comment by CG8516** [comment]
Ok, I'll add "ready" and sun cost when cycling plants.  

For the zombie alert, what if there was a subtle warning when only one has crossed, and a more intense one if there's more?

**Comment by Cyrax2001** [comment]
So, how would you handle the plant part? Would you just use "ready," or would you add states like "refreshing"?
And about point 3... I honestly don't know. I'm sure you'll come up with something good.
You know, I have a friend. He's 6 years old and blind, and he loves games. I know he would love Plants vs Zombies, but he doesn't have enough knowledge to download each beta version every time it's released. I hope that in the near future, the game is as accessible as it can be. That way, he won't need to download betas constantly and can feel satisfied completing the game by himself.
On my part, you should know that I've never been so interested in a project like this. I love offline games, I love strategy games, and I love Plants vs Zombies.
So, my friend, thank you very much.

**Comment by CG8516** [comment]
It will say "ready" or "refreshing", and the amount of sun you need.  
I just released beta 1.12, which hopefully covers everything you've requested. If not, let me know. 
The column detection is called "zombie tripwire".  

For now, it's probably best for your friend to wait until the mod is more complete.  
The first non-beta version will be out when every feature of the game is accessible, hopefuly some time next month.  
After that, I'll be shifting my focus to a new game, and will probably only make minor changes and bug fixes.

Until then, if you have any more suggestions, feel free to open a new issue.
