### ISSUE TITLE
Encounter a problem

### ISSUE THREAD

**Issue by piano777wzy** [CG8516/PvZA11y#15]
Hello, I found a problem. Let me describe it in detail.
When I started playing the game again, the first step was to create my own user, but I entered my user name and pressed enter, and that's what he said.
Steam Cloud Saving Active Steam Cloud save data is enabled so your saves will be stored in the cloud and will be accessi
Ble on any machine you log into. However this will overwrite any existing data you have on other machines. Hitting? Canc
El? Will disable Steam Cloud for this session.
That's what it says.
After that, the operation should be to use up and down to find ok and cancel, but when I press up and down on the keyboard, there is only a beep sound, without any hint, I try to press enter, there is no response, the screen reader will read the blank space, but can not find ok and cancel.
At this time, I started my ocr recognition function, and I went to the main menu through this step, hoping to solve this problem.
This problem does not arise 100%, and it is not necessarily the case every time.
Of course, sometimes ok can be found and canceled.

**Comment by CG8516** [comment]
Thanks for the report! I managed to reproduce the issue on my machine, and have just implemented a fix in the code.  
Will be included in the next update.

**Comment by piano777wzy** [comment]
ok








 ---Original---
From: ***@***.***&gt;
Date: Fri, Dec 22, 2023 20:20 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CG8516/PvZA11y] Encounter a problem (Issue #15)




 
Thanks for the report! I managed to reproduce the issue on my machine, and have just implemented a fix in the code.
 Will be included in the next update.
 
&mdash;

**Comment by CG8516** [comment]
Fixed in beta 1.13
