### ISSUE TITLE
Convey row information for fast zombie warning

### ISSUE THREAD

**Issue by guilevi** [CG8516/PvZA11y#17]
For zombies that trigger a fast-zombie warning, it might be worth modifying the pitched entry alert (e.g. three very short beeps instead of the current medium-length one). If I'm waiting to place a plant to intercept one, I currently have to either cycle through the zombies or use the sonar on all the rows to find out where it's coming from.

**Comment by CG8516** [comment]
Sure! That would be more useful than it is right now.

**Comment by CG8516** [comment]
Added in Beta 1.13. You can preview it by adjusting the volume of the alert in the accessibility settings.
