### ISSUE TITLE
a suggestion, and a problem with the menu to configure the inputs

### ISSUE THREAD

**Issue by Cyrax2001** [CG8516/PvZA11y#18]
Alright, I have a small issue, and fortunately, this time I tested it several times before reporting it, lol. The issue is that when I navigate the menu to reassign keyboard inputs, after scrolling down to those used to move through the zombies in a row, the mod crashes. I tried it multiple times, but it kept happening. The mod would restart, reporting a fatal error.
And the suggestion: it would be great if, in addition to the options to configure everything separately, you could restore the option to configure all keys at once. This is useful if you dislike the default mapping altogether and want to change everything. This way, you could do it without having to go through each individual option.
By the way, could you include a button to reset the keyboard map? Like the info 2 or something similar?

**Comment by CG8516** [comment]
Sorry to hear that. Beta 1.13 was just released, and it includes some stability improvements to the input system.  
Let me know if that fixed the crashing at all. If not, would you be able to share the crashlog.txt file in the mod's folder, and also your copy of the "PvzAccessibilityConfig.json" file?  

I'll add those other suggestions in the next update.

**Comment by Cyrax2001** [comment]
"Well, you fixed it! Thank you very much. There is still a certain strange error that causes, if the game is started first and then the mod, the mod restarts and generates this crashlock."
Solo se completó una parte de una solicitud ReadProcessMemory o WriteProcessMemory.   at System.Diagnostics.NtProcessManager.EnumProcessModulesUntilSuccess(SafeProcessHandle processHandle, IntPtr[] modules, Int32 size, Int32& needed, Int32 filterFlag)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at PvZA11y.Program.HookProcess()
   at PvZA11y.Program.SafeMain(String[] args)
   at PvZA11y.Program.Main(String[] args)Void EnumProcessModulesUntilSuccess(Microsoft.Win32.SafeHandles.SafeProcessHandle, IntPtr[], Int32, Int32 ByRef, Int32)System.Collections.ListDictionaryInternal
   "There is some text in Spanish. It's because it's my native language, and I play it in that language. While things like accents and ñ are not processed correctly, I trust that it's something you will fix. Although I admit that I would prefer to play it in English, but I don't know how to change the language."

**Comment by CG8516** [comment]
Beta 1.14 now includes options to rebind all inputs for keyboard or controller, and options to reset all keyboard or controller binds to their default values.  
Also added a potential fix for that crash, let me know if it still happens.
