### ISSUE TITLE
bug and suggest

### ISSUE THREAD

**Issue by rangga-w** [CG8516/PvZA11y#2]
I have tried the beta mod version for this game and I am very happy.
And this is my review so that the mod that is being developed will run better and be more comfortable when running it.
This mod still has a bug like the one I mentioned above, namely when it is run it sometimes closes by itself and that is very uncomfortable when the player is having fun playing.
Then, my suggestion is that there is an option to turn off the beep sound when the mod is used in the game. Because after I tried looking for this option but I couldn't find it
That's all my opinion this time, hopefully it can be improved further. Thanks for developing!

**Comment by CG8516** [comment]
Thanks for the report! I'll look into that issue.
For disabling beeps, you can currently turn audio cue volume to zero. It won't affect your screen reader volume.

In the future, I will add options to toggle specific categories (menu, moving around the board, switching plants, etc..)

**Comment by CG8516** [comment]
I've just implemented a fix for a crash in the audio engine. This crash would happen silently without restarting the mod, so is probably what caused the mod to seem to close by itself. 
Hopefully that's the issue you were facing. If not, feel free to reopen.

**Comment by rangga-w** [comment]
Thanks for improvemen. Now mod is more better.
Once again, thank you very much. Maybe, after this project you and team can develope another old game like zuma ect. greetings from Indonesia

**Comment by CG8516** [comment]
No problem! I'd love to work on more games after this one.
