### ISSUE TITLE
Suggestion: Support for displaying vase contents with Plantern in Vasebreaker levels

### ISSUE THREAD

**Issue by ferryboy001** [CG8516/PvZA11y#20]
Hello, I am a blind player who enjoys playing Plants vs Zombies with your amazing mod. Thank you for making this game accessible for me and other visually impaired players.

I have a suggestion for improving the accessibility of the Vasebreaker levels. Currently, when I use the Plantern plant, which is supposed to light up the vases and reveal their contents, the screen reader only says "vase" or "plant vase" for each vase. This makes it very hard to strategize and plan ahead, since I don't know what kind of zombies or plants are inside the vases.

I would like to suggest that the mod support displaying the vase contents with the Plantern plant, so that the screen reader can say something like "conehead vase", "sunflower vase", or "jack-in-the-box vase" for each vase. This would make the Vasebreaker levels more fun and challenging for blind players, and also more consistent with the original game design.

I hope you will consider this suggestion and implement it in a future update. Thank you for your hard work and dedication to making this game accessible.

**Comment by CG8516** [comment]
Hi, no problem at all. It's been really rewarding.  
I'll see what I can do about the vases, hopefully that will be in the next update.

**Comment by CG8516** [comment]
Beta 1.14 now supports this functionality :)
