### ISSUE TITLE
Suggestion for using keys that can be pressed twice.

### ISSUE THREAD

**Issue by Cyrax2001** [CG8516/PvZA11y#21]
Firstly, I wish you a nice day. It would be a nice night for me, but you understand me.
I propose two things. As we now have the ability to program certain information that is vocalized when a key is pressed twice, it could be utilized in a very good way.
First, I would suggest that instead of the info 4 key informing whether there is a lawnmower in the row, this information be provided by info 1 when pressed twice quickly. This way, it wouldn't have to be an option that is deactivated from the accessibility menu but rather information that is vocalized in a much more practical way. Why move it from info 4 to info 1? Simple, to have a sort of logic in the controls. This way, in addition to info 1 informing you about which zombies are in the row, it also informs you whether or not there is a lawnmower in that row.
My second idea would be that if you press info 3 quickly twice, it informs you of the amount of coins collected so far. It would be a good way to have it inform not only about the number of suns but also about the number of coins.
And a very small suggestion that I would like to propose as well... could you, please, please, add an option in the accessibility menu that activates automatic vocalization of the total number of suns collected when a sun is obtained? This last one is not very important, but I would like it a lot.
Thank you very much for reading!

**Comment by CG8516** [comment]
I understand you, it's almost night where I live :)

I like all three of those suggestions, and will try to get them all added in the next update.

**Comment by CG8516** [comment]
All three suggestions have been added in Beta 1.14
