### ISSUE TITLE
a couple of small problems in the almanac.

### ISSUE THREAD

**Issue by Cyrax2001** [CG8516/PvZA11y#22]
Firstly, when we surpass level 2-4, where we unlock the almanac, if we check it, we see that we have the "Ibnoshroom" already unlocked when it's not the case; in fact, it gets unlocked after the "Whack a Zombie" mini-game.
Secondly, when the Dolphin Zombie appears during gameplay, if we look for it in the almanac, it will be visually present. However, in the mod, it is stated as a mysterious zombie that has not been found yet.

**Comment by CG8516** [comment]
Hey, thanks for reporting this. I'll get those fixed in the next version.

**Comment by CG8516** [comment]
Fixed in Beta 1.15 :smile:
