### ISSUE TITLE
Issue with music track syncing during the wave

### ISSUE THREAD

**Issue by Cyrax2001** [CG8516/PvZA11y#23]
[problem with music tracks during waves.zip](https://github.com/CG8516/PvZA11y/files/13771850/problem.with.music.tracks.during.waves.zip)
Hello, my friend.
I've been experiencing an issue for some time now, and I'll explain the audio file I attached for clarification.
First, the wave is announced, so I freeze the game to check that I'm ready to face it. Then, when the sound of the sun being collected is heard, I unfreeze the game, and the wave music track goes completely out of sync with the main music track. It seems like it's trying to recover, but when I freeze the game again to check on the zombies, the music breaks again.

**Comment by CG8516** [comment]
Thanks for reporting. This is something I've also encountered, but I don't have a solid fix for it yet.  
Basically, when music is playing, a number increases to indicate how far along you are through the song.  
It uses this number to know when to start the other layers/tracks of music.
While the game is frozen, this number stops going up, which causes the extra tracks to come in at the wrong time.

It's definitely fixable, but may take some time.

**Comment by CG8516** [comment]
Beta 1.15 now patches the game's code, to keep the tracks in sync while the game is paused.
