### ISSUE TITLE
Glove mistakenly tries to sell a plant in Zen Garden

### ISSUE THREAD

**Issue by TPodtepa** [CG8516/PvZA11y#26]
When I try picking up a plant with the garden glove, Crazy Dave tells me he'll pay x amount for said plant, so it looks like it's trying to do the sell option instead.
If I want to actually use the glove, I have to go left 1, to where it says chocolate (I have none so it's chocolate 0), and click on that, and that works.

**Comment by CG8516** [comment]
Thanks for the report. Just patched the code, the fix will be in the next update :)

**Comment by CG8516** [comment]
Fixed in beta 1.15!
