### ISSUE TITLE
Suggestion: Add an optional setting for selecting plants

### ISSUE THREAD

**Issue by ferryboy001** [CG8516/PvZA11y#27]
Hi, I suggest adding a setting option that allows changing the user's behavior when switching plants with the numeric keypad or the plus and minus keys. One option is the current situation, which is to use chords to indicate the plant's readiness status, and the mouse does not move. The other option is to automatically use chords to indicate the plant's readiness, but when the user presses the numeric key or the plus and minus keys to switch to a certain plant, the mouse will click on that plant and pick it up, so that we can rely solely on the game's built-in sound effects to determine whether the plant can be planted, and also ensure that in the smash pot levels, the picked-up plant will not disappear quickly. At the same time, in this case, the planting behavior will only require clicking on the target grid, and not need to perform the current two-step action.
Since the above content is translated from Chinese, there may be some negligence or ambiguity in the expression, I look forward to hearing from you!

**Comment by CG8516** [comment]
I think an option to automatically try to place the plant when a number key is pressed would be good. Is that what you were suggesting?  
And then the voice/warnings the mod adds could also be optional. For those who want to rely more on the game's sounds.  

I'm not sure what you mean about the vase breaker levels though. Plants are supposed to disappear when they haven't been placed.  

If you're suggesting that the plants should always be clicked once, and held in the cursor, this will bring some issues.  
You're not able to collect sun or coins while holding a plant. You're also unable to break vases while holding a plant.

**Comment by ferryboy001** [comment]
Sorry, I forgot that doing this would cause problems. I just thought of using more of the game's built-in sound effects, such as ready and unable to plant, after all, they are already good enough. Regarding pressing the number keys to automatically plant, my suggestion is to provide a double-click option to avoid accidental touches, which might be better. Regarding the problems that my previous suggestion might cause, maybe they can only be temporarily avoided by automatically putting them down. But maybe, you can use the backtick to put down plants, although I know that backspace can achieve the same effect, but backtick might be easier to operate.

**Comment by Cyrax2001** [comment]
No. He refers to when you press a numeric key, the plant is selected from the top tray, and the sound of selecting the sound pack is heard, the sound that the game already has.
It would be something like this: press the numeric key, and the plant is clicked in the tray, so the selection sound is played. If it's not refreshed, you hear that sound when a plant is not usable. This way, the player could know if a plant is refreshed with a native option within the game.
I don't know if it would work, but well, maybe it will.
In fact, I was also thinking of something like this. It would be great if the shovel had a different behavior. Instead of pressing the shovel key on the plant, it would be nice if you pressed the shovel key and then pressed enter on the plant you want to remove. OK, enter, or the confirm button, you get the idea.

**Comment by Cyrax2001** [comment]
"I confess that I don't quite agree with the idea of pressing the numeric keys twice to plant.
Firstly, for someone like me, it would become a problem.
I am an impatient person, and I'm always pressing the numeric keys very quickly, waiting for them to recharge or to have the necessary suns to use them.
It's like when you click very quickly on the plant to use it as soon as it's ready.
Secondly, it would deviate from the original idea of gameplay.
I like the idea of selecting the plant and then placing it.
If you only have to press the key with that plant twice, it would take away some of the magic from the gameplay."

**Comment by CG8516** [comment]
Beta 1.15 adds an option to click each plant when you cycle to it.  
It will click the plant once, then right-click to release it.  
That way the sound effect can be played, but holding the plant won't prevent sun or coins from being collected.
