### ISSUE TITLE
Bug: imitator selection

### ISSUE THREAD

**Issue by Shadowcat42** [CG8516/PvZA11y#28]
This is just a minor bug I discovered while playing yesterday. The imitator support works, however if you turn on the imitator to fill out your very last slot, you'll be told to press start to begin the level, but pressing start doesn't actually do anything. This is consistently reproduceable, at least here.

**Comment by CG8516** [comment]
Thanks for reporting. Should be fixed in the next update.

**Comment by CG8516** [comment]
Fixed in beta 1.15!
