### ISSUE TITLE
Zen Garden: Buying the gold watering can doesn't stick

### ISSUE THREAD

**Issue by TPodtepa** [CG8516/PvZA11y#33]
I bought the gold watering can for the zen garden three times now. When I buy it, it disappears from the list, but when I backspace out of the store and re-enter the garden, I only have a normal watering can. I go back to the store, the watering can shows up as a purchasable item, but my 10k gold isn't back along with it.

**Comment by CG8516** [comment]
Oops, I'm so sorry about that.  
While I was trying to figure out what was wrong with marigold watering, I added code to set my watering can back to the normal one. I completely forgot to take that out again before releasing it.  
Just updated the 1.15 release, so it will no longer have this issue.

**Comment by TPodtepa** [comment]
No worries, farming gold isn't difficult and the watering can was the last item I needed other than tons of tree food anyway.
Thanks for fixing, and also for the mod as a whole. You've been doing a fantastic job and I'm sure I'm not the only person who appreciates being able to play this.
