### ISSUE TITLE
Suggestions for adding languages

### ISSUE THREAD

**Issue by piano777wzy** [CG8516/PvZA11y#39]
Hello! Regarding language files, we have a suggestion that we don’t know if it can be implemented, which is to let users add new sentences for translation. The reason for doing this is that the text information built into the game cannot be translated. In this way, when the user encounters the game You can add translations to your own text.

**Comment by CG8516** [comment]
Would you be able to clarify on this? Where do you want new sentences? Which ones can't be translated?

**Comment by piano777wzy** [comment]
> 你能澄清一下吗？你想要在哪里造句？哪些是不能翻译的？

Hello, I may not have made myself clear. Here's the thing. I'll use a few examples to describe it.
First of all, when you exit the game, there will be the following
Quit
Are you sure you wish to quit the game?
Quit
In this way, there is no way to translate
Let's move on to the following untranslatable content.
Quit Cancel
At this time, I want to change the name of my user profile. I went in like this.
WHO ARE YOU?
(Create a New User)
Next I'm going to delete and rename
Are You Sure?
This will permanently remove '8888' from the player roster!
Yes
Yes No
There are other places, so I won't go on with the examples.
Can we add entries to such content, or let us add these entries ourselves and translate them?

**Comment by CG8516** [comment]
Sorry for the late reply.  
This text is read from the game's memory, and is not included in the mod.  
Unfortunately, it can only be translated by applying a main.pak language mod to the game.
