### ISSUE TITLE
Suggested Method for Quickly Switching Plants

### ISSUE THREAD

**Issue by c469591** [CG8516/PvZA11y#4]
Hello, thank you to the author for the hard work in creating such a useful MOD. I have some suggestions regarding the plant switching option; currently, I feel that the switching is too slow, especially when not pausing.
I'd like to suggest a new method that allows players to quickly switch the plants they want to grow.
You can map plants to the number keys on the main keyboard,
for example, press 1 for Sunflower,
press 2 for Peashooter,
press 3 for Cherry Bomb,
and so on...
When the number of plants exceeds digits 1 to 0, you can use the equals sign and minus sign to flip through pages. Eventually, it could even allow players to customize the first page of plant options, placing the most frequently used ones on that page. Those are my thoughts; thank you!

**Comment by CG8516** [comment]
Great idea!  
You can't ever have more than 10 plants, so using the number keys would be perfect for this.  
It might also be cool to use the right analogue stick as a quick-select wheel (each angle/segment maps to a slot).  

Should be added in the next update.

**Comment by CG8516** [comment]
Added in beta 1.9
