### ISSUE TITLE
Continue/Repeat not working properly for minigames and puzzles

### ISSUE THREAD

**Issue by TPodtepa** [CG8516/PvZA11y#44]
If I hit "continue" after completing a minigame, it takes me to the very first one, ZomBotany. The same thing happens when I hit "repeat".
I noticed the same thing with puzzles, it takes me to Vasebreaker.

**Comment by CG8516** [comment]
That's a strange one, I can't seem to get the issue to happen on my end.  
I've tried both game versions, with minigames that have and haven't been completed.  
Choosing repeat also shouldn't be clicking anything, which makes this issue even stranger.  

Unfortunately, I probably won't be able to fix this until I can get the issue to happen on my machine.

**Comment by CG8516** [comment]
Fixed in [Beta 1.16](https://github.com/CG8516/PvZA11y/releases/tag/beta.1.16)
