### ISSUE TITLE
Portals not being read out in Portal Combat

### ISSUE THREAD

**Issue by TPodtepa** [CG8516/PvZA11y#45]
This occurs during the Portal Combat minigame, if the portal loads on a tile containing a plant, and also if a plant is placed on a tile where the portal is. F2 doesn't even tell if a portal is there.

**Comment by CG8516** [comment]
Thanks for the report. Just pushed a fix, which will be in the next update.  
This issue was introduced when I moved the tile info text to external files.

**Comment by CG8516** [comment]
Fixed in [Beta 1.16](https://github.com/CG8516/PvZA11y/releases/tag/beta.1.16)
