### ISSUE TITLE
Suggestion: Support refresh time notification for non-focused plants:

### ISSUE THREAD

**Issue by ferryboy001** [CG8516/PvZA11y#46]
You can enable or disable the refresh time notification by double-clicking the corresponding number key of the plant.

For example, at the beginning of the level, I mainly plant sunflowers and potato mines, so I can enable the refresh time notification for potato mines while planting sunflowers, and it can notify me in some way when it is ready.

 It can be a beep, but it should not be the same beep as the focused plant notification.
Considering that you may monitor the refresh time of multiple plants, you can consider notifying the name of the corresponding plant, or using a beep with the pitch of the location of the plant to indicate it.
Thank you!

**Comment by CG8516** [comment]
That's a good idea!  
For now, it will probably have to be for all plants, as having a per-level config will have a lot of edge-cases that will need to be tested and handled. Plus the input system will need to be reworked a bit, to allow people playing with a controller to use it.  

I've spent a bit of time on this, and have added an optional pitched and panned cue for all plants, which sounds similar to the current plant ready cue, but is different enough to know it's for the other plants.  
Plus it has a seperate volume slider, so you can make the alert quieter for unselected plants.  

This will be in the next update (coming very soon). Hopefully it will be a decent enough solution for now.  
I'll probably work on it more in a later update.

**Comment by CG8516** [comment]
Added in [Beta 1.16](https://github.com/CG8516/PvZA11y/releases/tag/beta.1.16)
