### ISSUE TITLE
Exception: Access Violation (code 0xc0000005) at address 005D83E7 in thread C60

### ISSUE THREAD

**Issue by c469591** [CG8516/PvZA11y#5]
Hello, I would like to inquire about an issue where the game crashes with an error report upon launching. How should this be resolved? I have already tried reinstalling Plants vs. Zombies, but the problem persists. Below is the error report:
[bug.txt](https://github.com/CG8516/PvZA11y/files/13691228/bug.txt)

**Comment by CG8516** [comment]
Does that only happen when you use the mod, or does it also happen when you launch it without the mod?

If it's the normal game, somebody on the steam discussions said they fixed a crash by disabling fullscreen mode: https://steamcommunity.com/app/3590/discussions/0/405692758703083839/

The mod actually includes a registry file that does the same thing, so maybe you could try that?
It's the "DisableFullscreen.reg" file in the "RegisteryKeys" folder.

**Comment by c469591** [comment]
The issue has been resolved; everything is working normally after I used the reg file. Thank you.
