### ISSUE TITLE
Can't find the delete profile option.

### ISSUE THREAD

**Issue by Tetrismonster** [CG8516/PvZA11y#6]
Hey.
Thanks so much for creating this mod!
Could you please make deleting a profile accessible?
Also, how do I turn down the music volume?

**Comment by CG8516** [comment]
No problem!
Music volume is the top choice in the options menu, you can use left/right inputs to decrease/increase volume.  

On the user picker screen, you can use info1 to rename a user, and info2 to delete a user.  

Sorry the controls aren't obvious or documented very well. I should make an effort to explain the possible inputs at each screen.

**Comment by Cyrax2001** [comment]
The good thing is that you had already done it. You just have to add an explanation in the text that is read when you press in  change user.
wow, friend, this mod is getting better and better!

**Comment by CG8516** [comment]
Beta 1.12 now has input cues for most of the menus (including this one)
