### ISSUE TITLE
Addition of a Verbalization for the Zombie's State

### ISSUE THREAD

**Issue by Cyrax2001** [CG8516/PvZA11y#8]
Hello, buddy! I really love your mod; "Plants vs Zombies" is a game I've always wanted to play, and I can do so thanks to you.
Now, here's my suggestion: take a look at this excerpt from the readme manual included in the game's installation folder on Steam:
"A zombie can typically endure some damage before it dies. When its arm drops off, it is close to dying. When its head drops off, it is dead and can no longer eat your plants, though its body may continue to move and block shots for a moment or two longer."
It would be fantastic if this information could also be displayed in-game, right next to the zombie. That way, it could be something like: "Zombie" when the zombie is healthy, "Zombie without arm" when its life is low, and "Zombie without head" when it's about to die. While not strictly necessary, as it's a visual way to express the zombie's health level, it would be great for adding more suspense for the player. Consider incorporating this enhancement!

**Comment by CG8516** [comment]
Hi, I'm glad you like it!

That's definitely something I want to add in the next update.
Many zombies have other visual indicators, too. Like the bucket head's bucket slowly gets more dinted, then falls off his head.
  
I just need to figure out the exact health values these things happen.

**Comment by CG8516** [comment]
Added in beta 1.11
